Add first draft
SEERNET/developer-docs pull request #1
Opened 2018-08-15 02:58 UTC by viveknimkarde

- Add first draft

2018-08-15 04:42 UTC, sushant-hiray requested changes
Check the markdown tables

2018-08-15 04:42 UTC, sushant-hiray commented on docs/realtime-speaker-identification-api.md
> +| start      | Float  | Start of the audio segment.           |
Fix table

2018-08-15 04:42 UTC, sushant-hiray commented on docs/realtime-speaker-identification-api.md
> +| offset    | Number | Segment offset from start of the audio. |
Fix table

2018-08-15 04:42 UTC, sushant-hiray commented on docs/speaker-enrollment-api.md
> +| sampleRate   | Number | Sample rate of the audio file.            |
Fix table

2018-08-15 04:42 UTC, sushant-hiray commented on docs/speaker-identification-api.md
> +| sampleRate   | Number       | Sample rate of the audio file.            |
Fix table

2018-08-20 05:47 UTC, viveknimkarde commented
@sushant-hiray can you merge this PR

2018-08-20 13:42 UTC, sushant-hiray approved these changes

2018-08-20 13:42 UTC, merged